package version

// DO NOT EDIT!
// file generated by scripts/generate-version-info.sh

const (
	commit_date int64 = 1775650970
	revision          = "470a6a49648468f853b5f9f9f1a36991d3ac91fd"
	branch            = "use-gen-version"
	version           = ""
)
