#!/bin/bash

# Generates go code with git version information to stdout

branch=${TAG_NAME:-${BRANCH_NAME:-$(git rev-parse --abbrev-ref HEAD)}}

revision=$(git rev-parse HEAD)
commit_date=$(git show -s --format=%ct) # unix timestamp

version=${TAG_NAME:-$(git describe --tags --exact-match 2> /dev/null)}

code=$(cat <<EOM
package version

// DO NOT EDIT!
// file generated by scripts/generate-version-info.sh

const (
	commit_date int64 = ${commit_date}
	revision          = "${revision}"
	branch            = "${branch}"
	version           = "${version}"
)
EOM
)

echo "${code}"